# Generated by Django 3.1 on 2020-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('image_service', models.ImageField(upload_to='')),
                ('nom_service', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('specialisteM', models.CharField(max_length=50, unique=True)),
                ('specialisteF', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
