# Generated by Django 3.1 on 2020-08-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('titre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_personnel', models.ImageField(default='imgdefaut.jpeg', upload_to='imgdefaut/')),
                ('nom_personnel', models.CharField(max_length=150)),
                ('prenom_personnel', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.titre')),
            ],
        ),
    ]
