# Generated by Django 3.1 on 2020-08-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_personnel_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo_personnel',
            field=models.ImageField(upload_to='imgdefaut/'),
        ),
    ]
